var _ = require('lodash');

var data = [
  {"Title":"Return of the Jedi","Year":"1983","Rated":"N/A","Released":"25 May 1983","Runtime":"N/A","Genre":"Action, Adventure, Sci-Fi","Director":"N/A","Writer":"N/A","Actors":"N/A","Plot":"With the rise of the empire shaking the galaxy at its core, the rebels are driven deep into hiding. The rebels risk all with one last strike. Is it redemption for the freedom of the galaxy ...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ2YTE0MmItODU3MC00MTQxLTg5NzQtYmIyZTVhOGQ2NjYwXkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.2","imdbVotes":"401","imdbID":"tt2301123","Type":"game","Response":"True"},
  {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 143 wins & 198 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.8","imdbVotes":"1,477,526","imdbID":"tt1375666","Type":"movie","Response":"True"},
  {"Title":"Jaws 2","Year":"1978","Rated":"PG","Released":"16 Jun 1978","Runtime":"116 min","Genre":"Adventure, Horror, Thriller","Director":"Jeannot Szwarc","Writer":"Peter Benchley (characters created by), Carl Gottlieb, Howard Sackler","Actors":"Roy Scheider, Lorraine Gary, Murray Hamilton, Joseph Mascolo","Plot":"Police chief Brody must protect the citizens of Amity after a second monstrous shark begins terrorizing the waters.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BN2U1MWE1NTMtYjQ2ZC00MTFmLWFmYjItODMyNGYxOTAyZmEzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.7","imdbVotes":"51,171","imdbID":"tt0077766","Type":"movie","Response":"True"},
  {"Title":"Titanic","Year":"1997","Rated":"PG-13","Released":"19 Dec 1997","Runtime":"194 min","Genre":"Drama, Romance","Director":"James Cameron","Writer":"James Cameron","Actors":"Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates","Plot":"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.","Language":"English","Country":"USA","Awards":"Won 11 Oscars. Another 110 wins & 73 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMzg1MDA0MTU2Nl5BMl5BanBnXkFtZTcwMTMzMjkxNw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"7.7","imdbVotes":"796,903","imdbID":"tt0120338","Type":"movie","Response":"True"},
  {"Title":"Avatar","Year":"2009","Rated":"PG-13","Released":"18 Dec 2009","Runtime":"162 min","Genre":"Action, Adventure, Fantasy","Director":"James Cameron","Writer":"James Cameron","Actors":"Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang","Plot":"A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.","Language":"English, Spanish","Country":"USA, UK","Awards":"Won 3 Oscars. Another 80 wins & 121 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg","Metascore":"83","imdbRating":"7.9","imdbVotes":"890,617","imdbID":"tt0499549","Type":"movie","Response":"True"},
  {"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Hampton Fancher (screenplay), David Webb Peoples (screenplay), Philip K. Dick (novel)","Actors":"Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos","Plot":"A blade runner must pursue and try to terminate four replicants who stole a ship in space and have returned to Earth to find their creator.","Language":"English, German, Cantonese, Japanese, Hungarian","Country":"USA, Hong Kong, UK","Awards":"Nominated for 2 Oscars. Another 11 wins & 16 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BZWZlYmEyYTItNGRjYy00ZmMxLWEzMWItM2Q2NjZlNTMwMjQ3XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg","Metascore":"89","imdbRating":"8.2","imdbVotes":"464,376","imdbID":"tt0083658","Type":"movie","Response":"True"},
  {"Title":"American Beauty","Year":"1999","Rated":"R","Released":"01 Oct 1999","Runtime":"122 min","Genre":"Drama, Romance","Director":"Sam Mendes","Writer":"Alan Ball","Actors":"Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley","Plot":"A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.","Language":"English","Country":"USA","Awards":"Won 5 Oscars. Another 103 wins & 96 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjM4NTI5NzYyNV5BMl5BanBnXkFtZTgwNTkxNTYxMTE@._V1_SX300.jpg","Metascore":"86","imdbRating":"8.4","imdbVotes":"827,773","imdbID":"tt0169547","Type":"movie","Response":"True"},
  {"Title":"There Will Be Blood","Year":"2007","Rated":"R","Released":"25 Jan 2008","Runtime":"158 min","Genre":"Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson (screenplay), Upton Sinclair (novel)","Actors":"Daniel Day-Lewis, Martin Stringer, Matthew Braden Stringer, Jacob Stringer","Plot":"A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.","Language":"English, American Sign Language","Country":"USA","Awards":"Won 2 Oscars. Another 105 wins & 133 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg","Metascore":"92","imdbRating":"8.1","imdbVotes":"375,662","imdbID":"tt0469494","Type":"movie","Response":"True"},
  {"Title":"The Bourne Identity","Year":"2002","Rated":"PG-13","Released":"14 Jun 2002","Runtime":"119 min","Genre":"Action, Mystery, Thriller","Director":"Doug Liman","Writer":"Tony Gilroy (screenplay), W. Blake Herron (screenplay), Robert Ludlum (novel)","Actors":"Matt Damon, Franka Potente, Chris Cooper, Clive Owen","Plot":"A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.","Language":"English, French, German, Dutch, Italian","Country":"USA, Germany, Czech Republic","Awards":"3 wins & 5 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDRmOGQ0ZjktMTQ5Zi00NTZlLTk5MjktOWY4ZjcyOGE5OGRlXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg","Metascore":"68","imdbRating":"7.9","imdbVotes":"412,477","imdbID":"tt0258463","Type":"movie","Response":"True"},
  {"Title":"Gone with the Wind","Year":"1939","Rated":"G","Released":"17 Jan 1940","Runtime":"238 min","Genre":"Drama, History, Romance","Director":"Victor Fleming, George Cukor, Sam Wood","Writer":"Margaret Mitchell (story of the old south \"Gone with the Wind\"), Sidney Howard (screenplay)","Actors":"Thomas Mitchell, Barbara O'Neil, Vivien Leigh, Evelyn Keyes","Plot":"A manipulative Southern belle carries on a turbulent affair with a blockade runner during the American Civil War.","Language":"English","Country":"USA","Awards":"Won 8 Oscars. Another 9 wins & 8 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BYTA4NzE5M2UtYWQwMC00YjNjLWJiNGEtYWJjYzkwNjIzMWUzXkEyXkFqcGdeQXVyNjc0MzMzNjA@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.2","imdbVotes":"216,610","imdbID":"tt0031381","Type":"movie","Response":"True"},
  {"Title":"The Many Adventures of Winnie the Pooh","Year":"1977","Rated":"G","Released":"11 Mar 1977","Runtime":"74 min","Genre":"Animation, Comedy, Family","Director":"John Lounsbery, Wolfgang Reitherman","Writer":"A.A. Milne (books), Larry Clemmons (story), Ralph Wright (story), Vance Gerry (story), Xavier Atencio (story), Ken Anderson (story), Julius Svendsen (story), Ted Berman (story), Eric Cleworth (story), Winston Hibler (story supervisor \"Blustery Day\")","Actors":"Sebastian Cabot, Junius Matthews, Barbara Luddy, Howard Morris","Plot":"A collection of animated shorts based on the stories and characters by A. A. Milne.","Language":"English","Country":"USA","Awards":"1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY3OTkyMzYwNV5BMl5BanBnXkFtZTcwMzkzODU0MQ@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.6","imdbVotes":"24,342","imdbID":"tt0076363","Type":"movie","Response":"True"},
  {"Title":"Rear Window","Year":"1954","Rated":"APPROVED","Released":"01 Sep 1954","Runtime":"112 min","Genre":"Mystery, Thriller","Director":"Alfred Hitchcock","Writer":"John Michael Hayes (screenplay), Cornell Woolrich (based on the short story by)","Actors":"James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter","Plot":"A wheelchair-bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.","Language":"English","Country":"USA","Awards":"Nominated for 4 Oscars. Another 6 wins & 8 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.5","imdbVotes":"317,965","imdbID":"tt0047396","Type":"movie","Response":"True"},
  {"Title":"Murder at 1600","Year":"1997","Rated":"R","Released":"18 Apr 1997","Runtime":"107 min","Genre":"Action, Crime, Drama","Director":"Dwight H. Little","Writer":"Wayne Beach, David Hodgin","Actors":"Wesley Snipes, Diane Lane, Daniel Benzali, Dennis Miller","Plot":"A 25 year old female White House staffer, Carla Town, is murdered in the White House. D.C. homicide detective Regis is assigned to investigate, only to find evidence suppressed by the ...","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM1ODY4ODUwOV5BMl5BanBnXkFtZTcwNTc0MjUyMQ@@._V1_SX300.jpg","Metascore":"47","imdbRating":"6.1","imdbVotes":"23,616","imdbID":"tt0119731","Type":"movie","Response":"True"},
  {"Title":"Harry Potter and the Deathly Hallows: Part 2","Year":"2011","Rated":"PG-13","Released":"15 Jul 2011","Runtime":"130 min","Genre":"Adventure, Drama, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe","Plot":"Harry, Ron and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.","Language":"English","Country":"USA, UK","Awards":"Nominated for 3 Oscars. Another 46 wins & 87 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY2MTk3MDQ1N15BMl5BanBnXkFtZTcwMzI4NzA2NQ@@._V1_SX300.jpg","Metascore":"87","imdbRating":"8.1","imdbVotes":"546,266","imdbID":"tt1201607","Type":"movie","Response":"True"},
  {"Title":"Indiana Jones and the Last Crusade","Year":"1989","Rated":"PG-13","Released":"24 May 1989","Runtime":"127 min","Genre":"Action, Adventure, Fantasy","Director":"Steven Spielberg","Writer":"Jeffrey Boam (screenplay), George Lucas (story), Menno Meyjes (story), George Lucas (characters), Philip Kaufman (characters)","Actors":"Harrison Ford, Sean Connery, Denholm Elliott, Alison Doody","Plot":"When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana Jones must follow in his father's footsteps and stop the Nazis.","Language":"English, German, Greek, Arabic","Country":"USA","Awards":"Won 1 Oscar. Another 6 wins & 20 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjNkMzc2N2QtNjVlNS00ZTk5LTg0MTgtODY2MDAwNTMwZjBjXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg","Metascore":"65","imdbRating":"8.3","imdbVotes":"518,949","imdbID":"tt0097576","Type":"movie","Response":"True"}

];


function list () {
  return _.cloneDeep(data);
}

function find (properties) {
  return _.cloneDeep(_.filter(properties));
}


var randArrayEl = function(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
};

module.exports = {  list: list, find: find };

var getFakeName = function() {
  var fakeFirsts = ['Nimit', 'Dave', 'Shanna', 'Charlotte', 'Scott', 'Ayana', 'Omri', 'Gabriel', 'Joe'];
  var fakeLasts = ['Hashington', 'Stackson', 'McQueue', 'OLogn', 'Ternary', 'Claujure', 'Dunderproto', 'Binder', 'Docsreader', 'Ecma'];
  return randArrayEl(fakeFirsts) + '-' + randArrayEl(fakeLasts);
};

var getFakeTweet = function() {
  var awesome_adj = ['awesome', 'breathtaking', 'amazing', 'funny', 'sweet', 'cool', 'wonderful', 'mindblowing'];
  return "Fullstack Academy is " + randArrayEl(awesome_adj) + "! The instructors are just so " + randArrayEl(awesome_adj) + ". #fullstacklove #codedreams";
};
