var _ = require('lodash');

var data = [
  {"Title":"Star Wars","Year":"1983","Rated":"N/A","Released":"01 May 1983","Runtime":"N/A","Genre":"Action, Adventure, Sci-Fi","Director":"N/A","Writer":"N/A","Actors":"Harrison Ford, Alec Guinness, Mark Hamill, James Earl Jones","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMWJhYWQ3ZTEtYTVkOS00ZmNlLWIxZjYtODZjNTlhMjMzNGM2XkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.9","imdbVotes":"356","imdbID":"tt0251413","Type":"game","Response":"True"},
  {"Title":"Batman","Year":"1989","Rated":"PG-13","Released":"23 Jun 1989","Runtime":"126 min","Genre":"Action, Adventure","Director":"Tim Burton","Writer":"Bob Kane (Batman characters), Sam Hamm (story), Sam Hamm (screenplay), Warren Skaaren (screenplay)","Actors":"Michael Keaton, Jack Nicholson, Kim Basinger, Robert Wuhl","Plot":"The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker.","Language":"English, French","Country":"USA, UK","Awards":"Won 1 Oscar. Another 9 wins & 22 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg","Metascore":"69","imdbRating":"7.6","imdbVotes":"271,082","imdbID":"tt0096895","Type":"movie","Response":"True"},
  {"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 143 wins & 198 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.8","imdbVotes":"1,477,526","imdbID":"tt1375666","Type":"movie","Response":"True"},
  {"Title":"Jaws 2","Year":"1978","Rated":"PG","Released":"16 Jun 1978","Runtime":"116 min","Genre":"Adventure, Horror, Thriller","Director":"Jeannot Szwarc","Writer":"Peter Benchley (characters created by), Carl Gottlieb, Howard Sackler","Actors":"Roy Scheider, Lorraine Gary, Murray Hamilton, Joseph Mascolo","Plot":"Police chief Brody must protect the citizens of Amity after a second monstrous shark begins terrorizing the waters.","Language":"English","Country":"USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BN2U1MWE1NTMtYjQ2ZC00MTFmLWFmYjItODMyNGYxOTAyZmEzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"5.7","imdbVotes":"51,171","imdbID":"tt0077766","Type":"movie","Response":"True"},
  {"Title":"Titanic","Year":"1997","Rated":"PG-13","Released":"19 Dec 1997","Runtime":"194 min","Genre":"Drama, Romance","Director":"James Cameron","Writer":"James Cameron","Actors":"Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates","Plot":"A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.","Language":"English","Country":"USA","Awards":"Won 11 Oscars. Another 110 wins & 73 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMzg1MDA0MTU2Nl5BMl5BanBnXkFtZTcwMTMzMjkxNw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"7.7","imdbVotes":"796,903","imdbID":"tt0120338","Type":"movie","Response":"True"},
  {"Title":"Avatar","Year":"2009","Rated":"PG-13","Released":"18 Dec 2009","Runtime":"162 min","Genre":"Action, Adventure, Fantasy","Director":"James Cameron","Writer":"James Cameron","Actors":"Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang","Plot":"A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.","Language":"English, Spanish","Country":"USA, UK","Awards":"Won 3 Oscars. Another 80 wins & 121 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg","Metascore":"83","imdbRating":"7.9","imdbVotes":"890,617","imdbID":"tt0499549","Type":"movie","Response":"True"},
  {"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Hampton Fancher (screenplay), David Webb Peoples (screenplay), Philip K. Dick (novel)","Actors":"Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos","Plot":"A blade runner must pursue and try to terminate four replicants who stole a ship in space and have returned to Earth to find their creator.","Language":"English, German, Cantonese, Japanese, Hungarian","Country":"USA, Hong Kong, UK","Awards":"Nominated for 2 Oscars. Another 11 wins & 16 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BZWZlYmEyYTItNGRjYy00ZmMxLWEzMWItM2Q2NjZlNTMwMjQ3XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg","Metascore":"89","imdbRating":"8.2","imdbVotes":"464,376","imdbID":"tt0083658","Type":"movie","Response":"True"},
  {"Title":"American Beauty","Year":"1999","Rated":"R","Released":"01 Oct 1999","Runtime":"122 min","Genre":"Drama, Romance","Director":"Sam Mendes","Writer":"Alan Ball","Actors":"Kevin Spacey, Annette Bening, Thora Birch, Wes Bentley","Plot":"A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.","Language":"English","Country":"USA","Awards":"Won 5 Oscars. Another 103 wins & 96 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjM4NTI5NzYyNV5BMl5BanBnXkFtZTgwNTkxNTYxMTE@._V1_SX300.jpg","Metascore":"86","imdbRating":"8.4","imdbVotes":"827,773","imdbID":"tt0169547","Type":"movie","Response":"True"},
  {"Title":"There Will Be Blood","Year":"2007","Rated":"R","Released":"25 Jan 2008","Runtime":"158 min","Genre":"Drama","Director":"Paul Thomas Anderson","Writer":"Paul Thomas Anderson (screenplay), Upton Sinclair (novel)","Actors":"Daniel Day-Lewis, Martin Stringer, Matthew Braden Stringer, Jacob Stringer","Plot":"A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.","Language":"English, American Sign Language","Country":"USA","Awards":"Won 2 Oscars. Another 105 wins & 133 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxODQ4MDU5NV5BMl5BanBnXkFtZTcwMDU4MjU1MQ@@._V1_SX300.jpg","Metascore":"92","imdbRating":"8.1","imdbVotes":"375,662","imdbID":"tt0469494","Type":"movie","Response":"True"},
  {"Title":"The Bourne Identity","Year":"2002","Rated":"PG-13","Released":"14 Jun 2002","Runtime":"119 min","Genre":"Action, Mystery, Thriller","Director":"Doug Liman","Writer":"Tony Gilroy (screenplay), W. Blake Herron (screenplay), Robert Ludlum (novel)","Actors":"Matt Damon, Franka Potente, Chris Cooper, Clive Owen","Plot":"A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.","Language":"English, French, German, Dutch, Italian","Country":"USA, Germany, Czech Republic","Awards":"3 wins & 5 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDRmOGQ0ZjktMTQ5Zi00NTZlLTk5MjktOWY4ZjcyOGE5OGRlXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg","Metascore":"68","imdbRating":"7.9","imdbVotes":"412,477","imdbID":"tt0258463","Type":"movie","Response":"True"}
];


function list () {
  return _.cloneDeep(data);
}

function find (properties) {
  return _.cloneDeep(_.filter(properties));
}


var randArrayEl = function(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
};

module.exports = {  list: list, find: find };

var getFakeName = function() {
  var fakeFirsts = ['Nimit', 'Dave', 'Shanna', 'Charlotte', 'Scott', 'Ayana', 'Omri', 'Gabriel', 'Joe'];
  var fakeLasts = ['Hashington', 'Stackson', 'McQueue', 'OLogn', 'Ternary', 'Claujure', 'Dunderproto', 'Binder', 'Docsreader', 'Ecma'];
  return randArrayEl(fakeFirsts) + '-' + randArrayEl(fakeLasts);
};

var getFakeTweet = function() {
  var awesome_adj = ['awesome', 'breathtaking', 'amazing', 'funny', 'sweet', 'cool', 'wonderful', 'mindblowing'];
  return "Fullstack Academy is " + randArrayEl(awesome_adj) + "! The instructors are just so " + randArrayEl(awesome_adj) + ". #fullstacklove #codedreams";
};
